lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from lab_7.views import (
    index, add_friend, validate_npm, friend_list_json, delete_friend, friend_list
)

urlpatterns = [
    url(r'^$',
        index,
        name='index'),
    url(r'^friend-list/$',
        friend_list,
        name='friend-list'),
    url(r'^add-friend/$',
        add_friend,
        name='add-friend'),
    url(r'^validate-npm/$',
        validate_npm,
        name='validate-npm'),
    url(r'^delete-friend/(?P<friend_id>[0-9]+)/$',
        delete_friend,
        name='delete-friend'),
    url(r'^get-friend-list/$',
        friend_list_json,
        name='get-friend-list')
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1, namespace='lab-1')),
    url(r'^lab-2-addon/', include(lab_2_addon, namespace='lab-2-addon')),
    url(r'^lab-2/', include(lab_2, namespace='lab-2')),
    url(r'^lab-3/', include(lab_3, namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10')),
    url(r'^$', RedirectView.as_view(url='/lab-10/')),
]

lab_7/models.py
from django.db import models

class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250)
    added_at = models.DateField(auto_now_add=True)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import Friend
from django.forms import model_to_dict
from .api_csui_helper.csui_helper import CSUIhelper
import os

response = {}
csui_helper = CSUIhelper()


def index(request):
    current_page = request.GET.get('page', 1)
    mahasiswa_list, total_page = csui_helper.instance.get_mahasiswa_list(current_page)
    friend_list = Friend.objects.all()
    html = 'lab_7/lab_7.html'
    response['mahasiswa_list'] = mahasiswa_list
    response['friend_list'] = friend_list
    response['pages'] = range(1, total_page+1)
    response['current_page'] = current_page
    return render(request, html, response)


def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)

def friend_list_json(request): # update
    friends = [model_to_dict(obj) for obj in Friend.objects.all()]
    return JsonResponse({"results": friends}, content_type='application/json')

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        npm = request.POST['npm']
        if (not Friend.objects.filter(npm=npm).exists()):
            name = request.POST['name']
            friend = Friend(friend_name=name, npm=npm)
            friend.save()
            return JsonResponse(model_to_dict(friend))
        else:
            return JsonResponse({'error': 'already friend'})


@csrf_exempt
def delete_friend(request, friend_id):
    Friend.objects.filter(id=friend_id).delete()
    return JsonResponse({'error': 'success'})


@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    data = {
        'is_taken': Friend.objects.filter(npm=npm).exists()
    }
    return JsonResponse(data)

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list">
        <div class="container">
            <div class="row">
            <h2> Teman Saya </h2>
            <div class="list-group" id="friend-list">
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        $( document ).ready(function () {
            $.ajax({
                method: "GET",
                url: "{% url 'lab-7:get-friend-list' %}",
                success: function (response) {
                    // console.log(response);
                    response.results.forEach(function(item) {
                        $("#friend-list").append('<a id="friend-'+item.id+'" class="list-group-item clearfix">'+
                            item.friend_name+' ('+item.npm+')'+
                        '<span class="delete" id="'+item.id+'" onclick="deleteFriend('+item.id+')">(delete)</span>');
                    });
                    if ($("#friend-list").children().length == 0) {
                        $("#friend-list").append('<div id="empty-alert" class="alert alert-danger text-center"><strong>Opps!</strong> Tidak ada teman</div>');
                    }
                },
                error: function(error){
                    //tampilkan pesan error
                }
            });
        });
        var deleteFriend = function(id) {
            $.ajax({
                method: "POST",
                url: "/lab-7/delete-friend/"+id+"/",
                success: function () {
                    $("#friend-"+id).remove();
                    if ($("#friend-list").children().length == 0) {
                        $("#friend-list").append('<div id="empty-alert" class="alert alert-danger text-center"><strong>Opps!</strong> Tidak ada teman</div>');
                    }
                }
            });

        }

    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
    {% block content %}
    <section name="mahasiswa-list" id="mahasiswa-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> Mahasiswa Fasilkom</h2>
                    <div class="list-group">
                        {% if mahasiswa_list %}
                            {% for mahasiswa in mahasiswa_list %}
                                <a class="list-group-item clearfix">
                                    {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                    <span class="pull-right">
                            <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                                Tambah sebagai teman
                            </span>
                        </span>
                                </a>
                            {% endfor %}

                        {% else %}
                            <div class="alert alert-danger text-center">
                                <strong>Opps!</strong> Tidak ada mahasiswa
                            </div>
                        {% endif %}
                    </div>
                    <ul class="pagination">
                        {% for i in pages %}
                        <li><a href="/lab-7/?page={{i}}">{{i}}</a></li>
                        {% endfor %}
                      </ul>
                </div>
                <div class="col-lg-4">
                    <h2> Teman Saya </h2>
                    <div class="list-group" id="friend-list">
                        {% if friend_list %}
                            {% for friend in friend_list %}
                                <a id="friend-{{friend.id}}" class="list-group-item clearfix">
                                    {{ friend.friend_name }} ({{ friend.npm }})
                                <span class="delete" id="{{friend.id}}" onclick="deleteFriend({{friend.id}})">(delete)</span>

                                </a>
                            {% endfor %}
                        {% else %}
                            <div id="empty-alert" class="alert alert-danger text-center">
                                <strong>Opps!</strong> Tidak ada teman
                            </div>
                        {% endif %}
                    </div>
                    <form id="add-friend" action="#">
                        {% csrf_token %}
                        <label for="field_npm">npm</label>
                        <input id="field_npm" type="text" name="npm" class="form-control"/>
                        <label for="field_name">name</label>
                        <input id="field_name" type="text" name="name" class="form-control"/>
                        <button type="submit">Tambah</button>
                    </form>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}

    {% block javascript %}
    <script>
        var addFriend = function(nama, npm) {
            if (nama && npm)
                $.ajax({
                    method: "POST",
                    url: "{% url "lab-7:add-friend" %}",
                    data: { name: nama, npm: npm},
                    success : function (friend) {
                        if (friend.id) {
                            html =
                                '<a id="friend-'+friend.id+'" class="list-group-item clearfix">' +
                                    friend.friend_name + ' ('+friend.npm+')' +
                                    '<span class="delete" id='+friend.id+' onclick="deleteFriend('+friend.id+')">(delete)</span>'
                                '</a>';
                        $("#friend-list").append(html)
                        if ($("#empty-alert")) $("#empty-alert").remove();
                        }
                    },
                });
        };

        var deleteFriend = function(id) {
            $.ajax({
                method: "POST",
                url: "/lab-7/delete-friend/"+id+"/",
                success: function () {
                    $("#friend-"+id).remove();
                    if ($("#friend-list").children().length == 0) {
                        $("#friend-list").append('<div id="empty-alert" class="alert alert-danger text-center"><strong>Opps!</strong> Tidak ada teman</div>');
                    }
                }
            });

        }
        $("#add-friend").on("submit", function (event) {
            event.preventDefault();

            name = $("#field_name").val()
            npm = $("#field_npm").val()
            addFriend(name, npm)
        });

        $("#field_npm").change(function () {
            console.log( $(this).val() );
            npm = $(this).val();
            $.ajax({
                method: "POST",
                url: '{% url "lab-7:validate-npm" %}',
                data: { 'npm': npm },
                dataType: 'json',
                success: function (data) {
                    if (data.is_taken) {
                        alert("Mahasiswa dengan npm seperti ini sudah ada");
                    }
                }
            });
        });
    </script>
    {% endblock %}